import SwiftUI
import Docent
import DocentUI

@main
struct DocentExampleApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}

struct ContentView: View {
    @State private var engine: DocentEngine?
    @State private var error: String?
    
    var body: some View {
        VStack {
            if let engine = engine {
                DocentSearchView(engine: engine)
            } else if let error = error {
                Text("Error: \(error)")
                    .foregroundColor(.red)
            } else {
                ProgressView("Loading knowledge base...")
                    .task {
                        await loadEngine()
                    }
            }
        }
    }
    
    private func loadEngine() async {
        do {
            // "Knowledge" is the default name generated by the plugin
            let docentEngine = try DocentEngine(resource: "Knowledge", bundle: .module)
            self.engine = docentEngine
        } catch {
            self.error = error.localizedDescription
        }
    }
}
